name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'new branch test'
        required: false
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  Cypress-Run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Cypress run
      uses: cypress-io/github-action@v6.6.1
      with:
        working-directory: .
